In [1]:
import pandas as pd
import numpy as np

In [2]:
recipes_df = pd.read_csv("data/Foodcom/recipes.csv")
reviews_df = pd.read_csv("data/Foodcom/reviews.csv")

In [3]:
print(recipes_df.shape)
recipes_df.info()
recipes_df.head()

(522517, 29)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 29 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Unnamed: 0                  522517 non-null  int64
 1   RecipeId                    522517 non-null  int64
 2   Name                        522517 non-null  object
 3   AuthorId                    522517 non-null  int64
 4   AuthorName                  522517 non-null  object
 5   CookTime                    439972 non-null  object
 6   PrepTime                    522517 non-null  object
 7   TotalTime                   522517 non-null  object
 8   DatePublished               522517 non-null  object
 9   Description                 522512 non-null  object
 10  Images                      522516 non-null  object
 11  RecipeCategory              521766 non-null  object
 12  Keywords                    505280 non-null  object
 13  RecipeIngredientQuantities  522514 non-null  object
 14  RecipeIngredientParts       522517 non-null  object
 15  AggregatedRating            269294 non-null  float64
 16  ReviewCount                 275028 non-null  float64
 17  Calories                    522517 non-null  float64
 18  FatContent                  522517 non-null  float64
 19  SaturatedFatContent         522517 non-null  float64
 20  CholesterolContent          522517 non-null  float64
 21  SodiumContent               522517 non-null  float64
 22  CarbohydrateContent         522517 non-null  float64
 23  FiberContent                522517 non-null  float64
 24  SugarContent                522517 non-null  float64
 25  ProteinContent              522517 non-null  float64
 26  RecipeServings              339606 non-null  float64
 27  RecipeYield                 174446 non-null  object
 28  RecipeInstructions          522517 non-null  object
dtypes: float64(12), int64(3), object(14)
memory usage: 115.6+ MB

,Unnamed: 0,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [4]:
reviews_df.info()
reviews_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1401982 entries, 0 to 1401981
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ReviewId       1401982 non-null  int64
 1   RecipeId       1401982 non-null  int64
 2   AuthorId       1401982 non-null  int64
 3   AuthorName     1401982 non-null  object
 4   Rating         1401982 non-null  int64
 5   Review         1401768 non-null  object
 6   DateSubmitted  1401982 non-null  object
 7   DateModified   1401982 non-null  object
dtypes: int64(4), object(4)
memory usage: 85.6+ MB

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z,2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13T21:15:00Z,2000-03-13T21:15:00Z
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28T12:51:00Z,2000-03-28T12:51:00Z